---
backup_user: backup
backup_home: "/home/{{ backup_user }}"
msmtp_account: default
msmtp_host: smtp.example.com
msmtp_from: backup@example.com
msmtp_user: backup@example.com
msmtp_port: 587
msmtp_password: "changeme"
archive_timer: "03:00"
archive_logfile: "{{ backup_home }}/archive.log"
